### ISSUE TITLE
How to add new vhost entry

### ISSUE THREAD

**Issue by aaravrana** [erpushpinderrana/dockerize-existing-drupal-project#6]
How to add new vhost entry within apache image?

**Comment by pushpinderchauhan** [comment]
If you want to add it in apache image then you need to follow below steps:

Add your custom vhost entry in local.apache.conf (https://github.com/erpushpinderrana/dockerize-existing-drupal-project/blob/master/apache/local.apache.conf). Say you want to create your local server name as localweb.com which points to /var/www/html/docroot/.

```
<VirtualHost *:80>
    ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://php:9000/var/www/html/docroot/$1
    DocumentRoot /var/www/html/docroot/
    ServerName localweb.com
    <Directory /var/www/html/docroot/>
        DirectoryIndex index.php
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
    
    # Manage apache and error logs
    CustomLog /proc/self/fd/1 common
    ErrorLog /proc/self/fd/2
</VirtualHost>
```

To update your `httpd.conf `, look for the old image so that we could recreate it. To list all the images in your container use the below command.

`docker image ls`

Remove the old apache image using the below command.

`docker image rm <image_id>`

Rebuild the container as usual so that it has newly added vhost entry using `docker-compose up -d`

You are all set now. Check in the browser with your custom URL e.g. localweb.com.

Also, don't forget to add the same in your host file. e.g. `127.0.0.1 localweb.com`

**Comment by gherardobertini** [comment]
If it can help I used also this vhost otherwise it wouldn't work with relative path for images.  
I changed `/var/www/html` to `/var/www/html/web`  
And you could edit PROJECT_ROOT in file `.env` 

```
# .env
...
PROJECT_ROOT=./docroot/drupal8
```

```
# apache/local.apache.conf
ServerName localhost

LoadModule deflate_module /usr/local/apache2/modules/mod_deflate.so
LoadModule proxy_module /usr/local/apache2/modules/mod_proxy.so
LoadModule proxy_fcgi_module /usr/local/apache2/modules/mod_proxy_fcgi.so
LoadModule rewrite_module /usr/local/apache2/modules/mod_rewrite.so

<VirtualHost *:80>
    # Php requests to port 9000 of the php-fpm container
    ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://php:9000/var/www/html/web/$1
    DocumentRoot /var/www/html/web
    <Directory /var/www/html/web>
        DirectoryIndex index.php
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
    
    # Manage apache and error logs
    CustomLog /proc/self/fd/1 common
    ErrorLog /proc/self/fd/2
</VirtualHost>
```
